# Export sprite modules as a TypeScript data file of text rows (docs/spec/art.md): the game compiles these into
# its atlas at load. Animation frames (keys "name~1", "name~2") are written as the rows that change from frame 0.
# Usage (from the repo root): python3 tools/pixelart/emit.py <out.ts> <EXPORT_NAME> <module> [module...]
#   e.g. python3 tools/pixelart/emit.py src/data/artLarge.ts LARGE_SPRITES large centerpieces
# Then register EXPORT_NAME in src/render/atlas.ts (once), and add ANIMS / LIGHTS entries in src/data/art.ts.
import os, sys, json, importlib
HERE = os.path.dirname(os.path.abspath(__file__))
sys.path[:0] = [HERE, os.path.join(HERE, "sprites")]

out_path, export, mods = sys.argv[1], sys.argv[2], [importlib.import_module(m) for m in sys.argv[3:]]
pals, sprites = {}, {}
for m in mods:
    pals.update(getattr(m, "PALS", {}))
    sprites.update(m.S)

def palname(p):
    if not p: return ""
    for name, v in pals.items():
        if v == p: return ", " + name
    raise SystemExit("local palette not named in the module's PALS: %r" % p)

def fmt(rows):
    return "\n".join("  " + ", ".join(json.dumps(r) for r in rows[i:i + 4]) + "," for i in range(0, len(rows), 4))

src = ", ".join(f"tools/pixelart/sprites/{m.__name__}.py" for m in mods)
out = [f"// GENERATED by tools/pixelart/emit.py from {src}: edit the sprite source and re-export, not this file.",
       "// Palette-indexed text sprites (docs/spec/art.md); animation frames list only the rows that change from frame 0.",
       'import { patch, type SpriteDef } from "./art";', ""]
for name, p in pals.items():
    out.append(f"const {name} = {{ " + ", ".join(f"{k}: {json.dumps(v)}" for k, v in p.items()) + " };")
out += ["", f"export const {export}: Record<string, SpriteDef> = {{}};",
        f"const add = (key: string, rows: string[], pal?: Record<string, string>) => {{ {export}[key] = {{ rows, pal, outline: true }}; }};", ""]
for k in [k for k in sprites if "~" not in k]:
    rows, pal = sprites[k]
    frames = sorted(f for f in sprites if f.startswith(k + "~"))
    fr = [sprites[f][0] for f in frames]
    if frames:  # frames share a canvas height; align them by the bottom (the footprint)
        h = max(len(rows), *(len(r) for r in fr))
        pad = lambda r: ["." * len(r[0])] * (h - len(r)) + r
        rows, fr = pad(rows), [pad(r) for r in fr]
    assert len({len(r) for r in rows}) == 1, f"{k}: rows differ in width"
    const = k.upper()
    out += [f"const {const} = [\n{fmt(rows)}\n];", f'add("{k}", {const}{palname(pal)});']
    for f, frows in zip(frames, fr):
        body = ", ".join(f"{i}: {json.dumps(r)}" for i, r in enumerate(frows) if r != rows[i])
        out.append(f'add("{f}", patch({const}, {{\n  {body},\n}}){palname(pal)});')
    out.append("")
open(out_path, "w").write("\n".join(out))
print(f"wrote {out_path}: {len(sprites)} sprites, {len(out)} lines")
